Lineage pull request for: skeleton
cisagov/vdp-scanner-terraform pull request #4
Opened 2021-06-03 06:10 UTC by cisagovbot

# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-tf-module.git`](https://github.com/cisagov/skeleton-tf-module.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

2021-06-03 13:03 UTC, jsf9k approved these changes
Nice job integrating the provider default tags jazz!

2021-06-03 17:41 UTC, dav3r requested changes
This PR needs to apply the late-breaking changes from https://github.com/cisagov/skeleton-tf-module/pull/51.

2021-06-03 20:56 UTC, mcdonnnj commented
> 
> 
> This PR needs to apply the late-breaking changes from [cisagov/skeleton-tf-module#51](https://github.com/cisagov/skeleton-tf-module/pull/51).

@dav3r Was just waiting for the changes to propagate. They've pulled down now so it should be good-to-go.

2021-06-03 21:07 UTC, jsf9k requested changes
@mcdonnnj, is this code meant to be a root module or just a Terraform module?  If the former then the `tags` variable should be present in `variables.tf`.  If the latter then you need to update the example code in `examples/basic_usage` to use your module.

2021-06-03 21:07 UTC, jsf9k commented on examples/basic_usage/variables.tf
> +  }
You can leave this as `default = {}` if you want.  In cisagov/skeleton-tf-module#51 I just wanted _something_ there so I could verify that the tags were being applied correctly.

2021-06-03 21:07 UTC, jsf9k commented on main.tf
> +  # details.
This file appears to be the example code from [cisagov/skeleton-tf-module](https://github.com/cisagov/skeleton-tf-module).  Do you intend to modify it to exercise your module?

2021-06-03 21:24 UTC, mcdonnnj commented
> 
> 
> @mcdonnnj, is this code meant to be a root module or just a Terraform module? If the former then the `tags` variable should be present in `variables.tf`. If the latter then you need to update the example code in `examples/basic_usage` to use your module.

@jsf9k This is effectively a placeholder repo right now. Since cloud native VDP scanning is on hold there is no actual Terraform for it currently. This was previously a direct clone of [cisagov/skeleton-tf-module](https://github.com/cisagov/skeleton-tf-module), but that caused it to miss any updates to that repo until I pushed https://github.com/cisagov/vdp-scanner-terraform/commit/83be81cd72ea50ed310498fb99b9f54bb355eb32 to update the [cisagov/action-lineage](https://github.com/cisagov/action-lineage) parent.

This PR is effectively it just pulling in all the updates to `cisagov/skeleton-tf-module` so that it's kept up-to-date until an actual implementation is begun.

2021-06-03 21:27 UTC, jsf9k commented
> > @mcdonnnj, is this code meant to be a root module or just a Terraform module? If the former then the `tags` variable should be present in `variables.tf`. If the latter then you need to update the example code in `examples/basic_usage` to use your module.
> 
> @jsf9k This is effectively a placeholder repo right now. Since cloud native VDP scanning is on hold there is no actual Terraform for it currently. This was previously a direct clone of [cisagov/skeleton-tf-module](https://github.com/cisagov/skeleton-tf-module), but that caused it to miss any updates to that repo until I pushed [83be81c](https://github.com/cisagov/vdp-scanner-terraform/commit/83be81cd72ea50ed310498fb99b9f54bb355eb32) to update the [cisagov/action-lineage](https://github.com/cisagov/action-lineage) parent.
> 
> This PR is effectively it just pulling in all the updates to `cisagov/skeleton-tf-module` so that it's kept up-to-date until an actual implementation is begun.

OK, so long as you grok the difference between a module and a root module.

Given what you said, is there any point in keeping this thing around and having to take care of and feed it?  You could just recreate it when that work picks up again.

2021-06-03 21:28 UTC, jsf9k approved these changes
I get it now @mcdonnnj.

2021-06-03 21:36 UTC, mcdonnnj commented
> 
> OK, so long as you grok the difference between a module and a root module.
> 
> Given what you said, is there any point in keeping this thing around and having to take care of and feed it? You could just recreate it when that work picks up again.

@jsf9k I'm fine with deleting it for now if we want to go that route.

2021-06-04 13:57 UTC, dav3r approved these changes
I'm good with whichever way you want to go on this @mcdonnnj.

2021-06-07 12:45 UTC, merged